# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: J&J Trekking
email: jjtrekking@domain.com
description: > # this means to ignore newlines until "baseurl:"
  La montagna è fatta per tutti, non solo per gli alpinisti:
  per coloro che desiderano il riposo nella quiete come per
  coloro che cercano nella fatica un riposo ancora più forte.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jjtrekking
github_username:  jjtrekking

# Build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  sass_dir: _sass

include: ['_pages']

# Collections
collections:
  tracks:
    output: true
    permalink: /itinerari/:path

# defaults
defaults:
  -
    scope:
      path: "itinerari"
      type: tracks
    values:
      layout: page
