# Site settings
title: J&J Trekking
description: > # this means to ignore newlines until "baseurl:"
  La montagna è fatta per tutti, non solo per gli alpinisti:
  per coloro che desiderano il riposo nella quiete come per
  coloro che cercano nella fatica un riposo ancora più forte.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jjtrekking.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

kramdown:
  input: GFM

include: ['_pages']

# Collections
collections:
  tracks:
    output: true
    permalink: /itinerari/:path

# Defaults (this does not seem to work on ghpages :P)
defaults:
  -
    scope:
      path: "itinerari"
      type: tracks
    values:
      layout: track
